remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ''
  - Intro to Jupyter, Generating Tapis v3 token:
    - Intro to Jupyter : block1/intro-to-jupyter
    - Generating a Tapis v3 token: block1/tapis-v3-token
  - Intro to Tapis Systems:
    - Intro to Tapis Systems: block3/tapis-systems
  - Intro to Tapis Apps:
    - Intro to Apps: block4/apps
  - Intro to Tapis Jobs:
    - Intro to Tapis Jobs: block4/jobs
    - Job outputs and sharing results: block4/jobs
  - Intro to Tapis UI:
    - Intro to Tapis UI: block5/intro

theme: jekyll-theme-time-machine
